Repository SOPT-all/35-COLLABORATION-SERVER-CARROT, pull requests merged in 2024-11, with the labels that each got.

#2 [feat] 프로젝트 초기 설정
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sopt/carrot_server/CarrotServerApplication.java
  src/main/resources/application.properties
  src/test/java/com/sopt/carrot_server/CarrotServerApplicationTests.java
Labels: ⚙️ Setting

#4 [Setting] 엔티티 설계
  .gitattributes
  .gitignore
  build.gradle
  src/main/java/com/sopt/carrot_server/CarrotServerApplication.java
  src/main/java/com/sopt/carrot_server/app/domain/Address.java
  src/main/java/com/sopt/carrot_server/app/domain/Product.java
  src/main/java/com/sopt/carrot_server/app/domain/User.java
  src/main/java/com/sopt/carrot_server/app/domain/common/BaseTimeEntity.java
  src/main/java/com/sopt/carrot_server/app/domain/enums/Category.java
  src/main/resources/application.properties
Labels: ✨ feature, ⚙️ Setting

#9 [Feat] 상세> 유저 정보 API
  src/main/java/com/sopt/carrot_server/app/application/UserService.java
  src/main/java/com/sopt/carrot_server/app/domain/repository/AddressRepository.java
  src/main/java/com/sopt/carrot_server/app/domain/repository/UserRepository.java
  src/main/java/com/sopt/carrot_server/app/dto/response/UserResponse.java
  src/main/java/com/sopt/carrot_server/app/mapper/UserMapper.java
  src/main/java/com/sopt/carrot_server/app/presentation/UserController.java
  src/main/java/com/sopt/carrot_server/global/common/code/FailureCode.java
  src/main/java/com/sopt/carrot_server/global/common/exception/AddressException.java
Labels: ✨ feature, 상품상세

#11 [Feat] 검색 > 상품 목록 조회 구현
  src/main/java/com/sopt/carrot_server/app/application/.gitkeep
  src/main/java/com/sopt/carrot_server/app/application/SearchService.java
  src/main/java/com/sopt/carrot_server/app/application/UserService.java
  src/main/java/com/sopt/carrot_server/app/domain/Address.java
  src/main/java/com/sopt/carrot_server/app/domain/Product.java
  src/main/java/com/sopt/carrot_server/app/domain/User.java
  src/main/java/com/sopt/carrot_server/app/domain/repository/AddressRepository.java
  src/main/java/com/sopt/carrot_server/app/domain/repository/ProductRepository.java
  src/main/java/com/sopt/carrot_server/app/dto/response/.gitkeep
  src/main/java/com/sopt/carrot_server/app/dto/response/SearchProductDetailResponse.java
  src/main/java/com/sopt/carrot_server/app/dto/response/SearchProductListResponse.java
  src/main/java/com/sopt/carrot_server/app/mapper/.gitkeep
  src/main/java/com/sopt/carrot_server/app/mapper/ProductMapper.java
  src/main/java/com/sopt/carrot_server/app/presentation/.gitkeep
  src/main/java/com/sopt/carrot_server/app/presentation/SerachController.java
  src/main/java/com/sopt/carrot_server/app/presentation/UserController.java
  src/main/java/com/sopt/carrot_server/global/common/code/SuccessCode.java
  src/main/java/com/sopt/carrot_server/global/common/dto/SuccessResponse.java
Labels: ✨ feature, 검색화면

#14 [Feat] 상세 > 게시물 설명, 상품 이미지
  src/main/java/com/sopt/carrot_server/app/application/ProductService.java
  src/main/java/com/sopt/carrot_server/app/domain/Product.java
  src/main/java/com/sopt/carrot_server/app/domain/repository/ProductRepository.java
  src/main/java/com/sopt/carrot_server/app/dto/response/ProductDetailResponse.java
  src/main/java/com/sopt/carrot_server/app/mapper/ProductMapper.java
  src/main/java/com/sopt/carrot_server/app/presentation/ProductController.java
  src/main/java/com/sopt/carrot_server/app/presentation/UserController.java
  src/main/java/com/sopt/carrot_server/global/common/code/SuccessCode.java
  src/main/java/com/sopt/carrot_server/global/common/exception/AddressException.java
  src/main/java/com/sopt/carrot_server/global/common/exception/ProductException.java
Labels: ✨ feature, 상품상세

#17 [Feat] 카테고리 목록 조회
  src/main/java/com/sopt/carrot_server/app/application/ProductService.java
  src/main/java/com/sopt/carrot_server/app/domain/enums/Category.java
  src/main/java/com/sopt/carrot_server/app/dto/response/ProductCategoryListResponse.java
  src/main/java/com/sopt/carrot_server/app/mapper/ProductMapper.java
  src/main/java/com/sopt/carrot_server/app/presentation/ProductController.java
  src/main/java/com/sopt/carrot_server/global/common/code/SuccessCode.java
Labels: ✨ feature

#18 [Feat] 홈 > 상품 목록
  src/main/java/com/sopt/carrot_server/CarrotServerApplication.java
  src/main/java/com/sopt/carrot_server/app/application/ProductService.java
  src/main/java/com/sopt/carrot_server/app/domain/repository/ProductRepository.java
  src/main/java/com/sopt/carrot_server/app/dto/response/HomeProductDetailResponse.java
  src/main/java/com/sopt/carrot_server/app/dto/response/HomeProductListResponse.java
  src/main/java/com/sopt/carrot_server/app/mapper/ProductMapper.java
  src/main/java/com/sopt/carrot_server/app/presentation/ProductController.java
  src/main/java/com/sopt/carrot_server/global/common/code/SuccessCode.java
Labels: ✨ feature, 홈화면
